# Generated by Django 2.1.1 on 2019-01-02 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('recieveFlag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('fromshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromshop', to='zaiko.Shop')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaiko.Item')),
                ('toshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toshop', to='zaiko.Shop')),
            ],
        ),
        migrations.RenameField(
            model_name='stockstatus',
            old_name='pub_date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='stockstatus',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
