# Generated by Django 2.1.1 on 2019-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0002_shippingorder_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
