# Generated by Django 2.1.1 on 2019-01-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0002_auto_20190102_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingHistory',
            new_name='ShippingOrder',
        ),
    ]
