# Generated by Django 2.1.1 on 2019-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0004_shop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
