# Generated by Django 2.1.1 on 2019-01-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0005_auto_20190115_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
