# Generated by Django 2.1.1 on 2019-02-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0007_auto_20190116_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
