# Generated by Django 2.1.1 on 2019-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0010_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
