# Generated by Django 2.1.1 on 2019-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0011_shippingorder_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingorder',
            name='totalprice',
        ),
    ]
