# Generated by Django 2.1.1 on 2019-03-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0014_remove_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
